### ISSUE TITLE
ATTENTION: UNOPTOMIZED CODE

### ISSUE THREAD

**Issue by ghost** [omn0mn0m/Balloon-Catheterization#37]
https://github.com/omn0mn0m/Balloon-Catheterization/blob/1bed92739ce04ede9d7b6f71fc7439a8aadb9d34/src/main.cpp#L66

while(1) is very inefficient. Each iteration the compiler must check if 1 is 1. This check is taking away cycles from your micro controller. If you use for(;;) there will be no check.

**Comment by omn0mn0m** [comment]
While this would be true back in the 90s, most compilers will change the opcode for while (1) and for(;;) to be the same. In this case, while (1) was chose for clarity.
